/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UkraineWarMapRouteImport } from './routes/ukraine-war-map'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingIndexRouteImport } from './routes/briefing.index'
import { Route as DeepDiveSectionRouteImport } from './routes/deep-dive.$section'
import { Route as BriefingDateRouteImport } from './routes/briefing.$date'
import { Route as BackgroundWorldWar3RiskRouteImport } from './routes/background.world-war-3-risk'
import { Route as BackgroundWillIndiaPakistanGoToWarAgainRouteImport } from './routes/background.will-india-pakistan-go-to-war-again'
import { Route as BackgroundWillChinaInvadeTaiwanRouteImport } from './routes/background.will-china-invade-taiwan'
import { Route as BackgroundWhySudanIsAtWarRouteImport } from './routes/background.why-sudan-is-at-war'
import { Route as BackgroundVenezuelaCubaCrisisExplainedRouteImport } from './routes/background.venezuela-cuba-crisis-explained'
import { Route as BackgroundUsChinaGreatPowerRivalryExplainedRouteImport } from './routes/background.us-china-great-power-rivalry-explained'
import { Route as BackgroundStraitOfHormuzRouteImport } from './routes/background.strait-of-hormuz'
import { Route as BackgroundRussianCasualtiesUkraineRouteImport } from './routes/background.russian-casualties-ukraine'
import { Route as BackgroundRedSeaCrisisRouteImport } from './routes/background.red-sea-crisis'
import { Route as BackgroundPakistanAfghanistanWarExplainedRouteImport } from './routes/background.pakistan-afghanistan-war-explained'
import { Route as BackgroundNuclearWeaponsByCountryRouteImport } from './routes/background.nuclear-weapons-by-country'
import { Route as BackgroundNorthKoreaRussiaMilitaryAllianceRouteImport } from './routes/background.north-korea-russia-military-alliance'
import { Route as BackgroundIsTheUsAtWarRouteImport } from './routes/background.is-the-us-at-war'
import { Route as BackgroundIsTheLebanonCeasefireHoldingRouteImport } from './routes/background.is-the-lebanon-ceasefire-holding'
import { Route as BackgroundIsTheGazaCeasefireHoldingRouteImport } from './routes/background.is-the-gaza-ceasefire-holding'
import { Route as BackgroundHezbollahCapabilitiesRouteImport } from './routes/background.hezbollah-capabilities'
import { Route as BackgroundDrcM23ConflictExplainedRouteImport } from './routes/background.drc-m23-conflict-explained'
import { Route as BackgroundBelarusRoleRussiaUkraineWarRouteImport } from './routes/background.belarus-role-russia-ukraine-war'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const UkraineWarMapRoute = UkraineWarMapRouteImport.update({
  id: '/ukraine-war-map',
  path: '/ukraine-war-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingIndexRoute = BriefingIndexRouteImport.update({
  id: '/briefing/',
  path: '/briefing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDiveSectionRoute = DeepDiveSectionRouteImport.update({
  id: '/deep-dive/$section',
  path: '/deep-dive/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingDateRoute = BriefingDateRouteImport.update({
  id: '/briefing/$date',
  path: '/briefing/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundWorldWar3RiskRoute = BackgroundWorldWar3RiskRouteImport.update({
  id: '/background/world-war-3-risk',
  path: '/background/world-war-3-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundWillIndiaPakistanGoToWarAgainRoute =
  BackgroundWillIndiaPakistanGoToWarAgainRouteImport.update({
    id: '/background/will-india-pakistan-go-to-war-again',
    path: '/background/will-india-pakistan-go-to-war-again',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundWillChinaInvadeTaiwanRoute =
  BackgroundWillChinaInvadeTaiwanRouteImport.update({
    id: '/background/will-china-invade-taiwan',
    path: '/background/will-china-invade-taiwan',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundWhySudanIsAtWarRoute =
  BackgroundWhySudanIsAtWarRouteImport.update({
    id: '/background/why-sudan-is-at-war',
    path: '/background/why-sudan-is-at-war',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundVenezuelaCubaCrisisExplainedRoute =
  BackgroundVenezuelaCubaCrisisExplainedRouteImport.update({
    id: '/background/venezuela-cuba-crisis-explained',
    path: '/background/venezuela-cuba-crisis-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundUsChinaGreatPowerRivalryExplainedRoute =
  BackgroundUsChinaGreatPowerRivalryExplainedRouteImport.update({
    id: '/background/us-china-great-power-rivalry-explained',
    path: '/background/us-china-great-power-rivalry-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundStraitOfHormuzRoute =
  BackgroundStraitOfHormuzRouteImport.update({
    id: '/background/strait-of-hormuz',
    path: '/background/strait-of-hormuz',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundRussianCasualtiesUkraineRoute =
  BackgroundRussianCasualtiesUkraineRouteImport.update({
    id: '/background/russian-casualties-ukraine',
    path: '/background/russian-casualties-ukraine',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundRedSeaCrisisRoute = BackgroundRedSeaCrisisRouteImport.update({
  id: '/background/red-sea-crisis',
  path: '/background/red-sea-crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundPakistanAfghanistanWarExplainedRoute =
  BackgroundPakistanAfghanistanWarExplainedRouteImport.update({
    id: '/background/pakistan-afghanistan-war-explained',
    path: '/background/pakistan-afghanistan-war-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundNuclearWeaponsByCountryRoute =
  BackgroundNuclearWeaponsByCountryRouteImport.update({
    id: '/background/nuclear-weapons-by-country',
    path: '/background/nuclear-weapons-by-country',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundNorthKoreaRussiaMilitaryAllianceRoute =
  BackgroundNorthKoreaRussiaMilitaryAllianceRouteImport.update({
    id: '/background/north-korea-russia-military-alliance',
    path: '/background/north-korea-russia-military-alliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundIsTheUsAtWarRoute = BackgroundIsTheUsAtWarRouteImport.update({
  id: '/background/is-the-us-at-war',
  path: '/background/is-the-us-at-war',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundIsTheLebanonCeasefireHoldingRoute =
  BackgroundIsTheLebanonCeasefireHoldingRouteImport.update({
    id: '/background/is-the-lebanon-ceasefire-holding',
    path: '/background/is-the-lebanon-ceasefire-holding',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundIsTheGazaCeasefireHoldingRoute =
  BackgroundIsTheGazaCeasefireHoldingRouteImport.update({
    id: '/background/is-the-gaza-ceasefire-holding',
    path: '/background/is-the-gaza-ceasefire-holding',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundHezbollahCapabilitiesRoute =
  BackgroundHezbollahCapabilitiesRouteImport.update({
    id: '/background/hezbollah-capabilities',
    path: '/background/hezbollah-capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundDrcM23ConflictExplainedRoute =
  BackgroundDrcM23ConflictExplainedRouteImport.update({
    id: '/background/drc-m23-conflict-explained',
    path: '/background/drc-m23-conflict-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundBelarusRoleRussiaUkraineWarRoute =
  BackgroundBelarusRoleRussiaUkraineWarRouteImport.update({
    id: '/background/belarus-role-russia-ukraine-war',
    path: '/background/belarus-role-russia-ukraine-war',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukraine-war-map': typeof UkraineWarMapRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/belarus-role-russia-ukraine-war': typeof BackgroundBelarusRoleRussiaUkraineWarRoute
  '/background/drc-m23-conflict-explained': typeof BackgroundDrcM23ConflictExplainedRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/is-the-gaza-ceasefire-holding': typeof BackgroundIsTheGazaCeasefireHoldingRoute
  '/background/is-the-lebanon-ceasefire-holding': typeof BackgroundIsTheLebanonCeasefireHoldingRoute
  '/background/is-the-us-at-war': typeof BackgroundIsTheUsAtWarRoute
  '/background/north-korea-russia-military-alliance': typeof BackgroundNorthKoreaRussiaMilitaryAllianceRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/pakistan-afghanistan-war-explained': typeof BackgroundPakistanAfghanistanWarExplainedRoute
  '/background/red-sea-crisis': typeof BackgroundRedSeaCrisisRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/us-china-great-power-rivalry-explained': typeof BackgroundUsChinaGreatPowerRivalryExplainedRoute
  '/background/venezuela-cuba-crisis-explained': typeof BackgroundVenezuelaCubaCrisisExplainedRoute
  '/background/why-sudan-is-at-war': typeof BackgroundWhySudanIsAtWarRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/will-india-pakistan-go-to-war-again': typeof BackgroundWillIndiaPakistanGoToWarAgainRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/briefing/$date': typeof BriefingDateRoute
  '/deep-dive/$section': typeof DeepDiveSectionRoute
  '/briefing/': typeof BriefingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukraine-war-map': typeof UkraineWarMapRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/belarus-role-russia-ukraine-war': typeof BackgroundBelarusRoleRussiaUkraineWarRoute
  '/background/drc-m23-conflict-explained': typeof BackgroundDrcM23ConflictExplainedRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/is-the-gaza-ceasefire-holding': typeof BackgroundIsTheGazaCeasefireHoldingRoute
  '/background/is-the-lebanon-ceasefire-holding': typeof BackgroundIsTheLebanonCeasefireHoldingRoute
  '/background/is-the-us-at-war': typeof BackgroundIsTheUsAtWarRoute
  '/background/north-korea-russia-military-alliance': typeof BackgroundNorthKoreaRussiaMilitaryAllianceRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/pakistan-afghanistan-war-explained': typeof BackgroundPakistanAfghanistanWarExplainedRoute
  '/background/red-sea-crisis': typeof BackgroundRedSeaCrisisRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/us-china-great-power-rivalry-explained': typeof BackgroundUsChinaGreatPowerRivalryExplainedRoute
  '/background/venezuela-cuba-crisis-explained': typeof BackgroundVenezuelaCubaCrisisExplainedRoute
  '/background/why-sudan-is-at-war': typeof BackgroundWhySudanIsAtWarRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/will-india-pakistan-go-to-war-again': typeof BackgroundWillIndiaPakistanGoToWarAgainRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/briefing/$date': typeof BriefingDateRoute
  '/deep-dive/$section': typeof DeepDiveSectionRoute
  '/briefing': typeof BriefingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukraine-war-map': typeof UkraineWarMapRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/belarus-role-russia-ukraine-war': typeof BackgroundBelarusRoleRussiaUkraineWarRoute
  '/background/drc-m23-conflict-explained': typeof BackgroundDrcM23ConflictExplainedRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/is-the-gaza-ceasefire-holding': typeof BackgroundIsTheGazaCeasefireHoldingRoute
  '/background/is-the-lebanon-ceasefire-holding': typeof BackgroundIsTheLebanonCeasefireHoldingRoute
  '/background/is-the-us-at-war': typeof BackgroundIsTheUsAtWarRoute
  '/background/north-korea-russia-military-alliance': typeof BackgroundNorthKoreaRussiaMilitaryAllianceRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/pakistan-afghanistan-war-explained': typeof BackgroundPakistanAfghanistanWarExplainedRoute
  '/background/red-sea-crisis': typeof BackgroundRedSeaCrisisRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/us-china-great-power-rivalry-explained': typeof BackgroundUsChinaGreatPowerRivalryExplainedRoute
  '/background/venezuela-cuba-crisis-explained': typeof BackgroundVenezuelaCubaCrisisExplainedRoute
  '/background/why-sudan-is-at-war': typeof BackgroundWhySudanIsAtWarRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/will-india-pakistan-go-to-war-again': typeof BackgroundWillIndiaPakistanGoToWarAgainRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/briefing/$date': typeof BriefingDateRoute
  '/deep-dive/$section': typeof DeepDiveSectionRoute
  '/briefing/': typeof BriefingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conflicts'
    | '/feed.xml'
    | '/mcp'
    | '/sitemap.xml'
    | '/ukraine-war-map'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/belarus-role-russia-ukraine-war'
    | '/background/drc-m23-conflict-explained'
    | '/background/hezbollah-capabilities'
    | '/background/is-the-gaza-ceasefire-holding'
    | '/background/is-the-lebanon-ceasefire-holding'
    | '/background/is-the-us-at-war'
    | '/background/north-korea-russia-military-alliance'
    | '/background/nuclear-weapons-by-country'
    | '/background/pakistan-afghanistan-war-explained'
    | '/background/red-sea-crisis'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/us-china-great-power-rivalry-explained'
    | '/background/venezuela-cuba-crisis-explained'
    | '/background/why-sudan-is-at-war'
    | '/background/will-china-invade-taiwan'
    | '/background/will-india-pakistan-go-to-war-again'
    | '/background/world-war-3-risk'
    | '/briefing/$date'
    | '/deep-dive/$section'
    | '/briefing/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conflicts'
    | '/feed.xml'
    | '/mcp'
    | '/sitemap.xml'
    | '/ukraine-war-map'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/belarus-role-russia-ukraine-war'
    | '/background/drc-m23-conflict-explained'
    | '/background/hezbollah-capabilities'
    | '/background/is-the-gaza-ceasefire-holding'
    | '/background/is-the-lebanon-ceasefire-holding'
    | '/background/is-the-us-at-war'
    | '/background/north-korea-russia-military-alliance'
    | '/background/nuclear-weapons-by-country'
    | '/background/pakistan-afghanistan-war-explained'
    | '/background/red-sea-crisis'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/us-china-great-power-rivalry-explained'
    | '/background/venezuela-cuba-crisis-explained'
    | '/background/why-sudan-is-at-war'
    | '/background/will-china-invade-taiwan'
    | '/background/will-india-pakistan-go-to-war-again'
    | '/background/world-war-3-risk'
    | '/briefing/$date'
    | '/deep-dive/$section'
    | '/briefing'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/conflicts'
    | '/feed.xml'
    | '/mcp'
    | '/sitemap.xml'
    | '/ukraine-war-map'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/belarus-role-russia-ukraine-war'
    | '/background/drc-m23-conflict-explained'
    | '/background/hezbollah-capabilities'
    | '/background/is-the-gaza-ceasefire-holding'
    | '/background/is-the-lebanon-ceasefire-holding'
    | '/background/is-the-us-at-war'
    | '/background/north-korea-russia-military-alliance'
    | '/background/nuclear-weapons-by-country'
    | '/background/pakistan-afghanistan-war-explained'
    | '/background/red-sea-crisis'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/us-china-great-power-rivalry-explained'
    | '/background/venezuela-cuba-crisis-explained'
    | '/background/why-sudan-is-at-war'
    | '/background/will-china-invade-taiwan'
    | '/background/will-india-pakistan-go-to-war-again'
    | '/background/world-war-3-risk'
    | '/briefing/$date'
    | '/deep-dive/$section'
    | '/briefing/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictsRoute: typeof ConflictsRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UkraineWarMapRoute: typeof UkraineWarMapRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BackgroundBelarusRoleRussiaUkraineWarRoute: typeof BackgroundBelarusRoleRussiaUkraineWarRoute
  BackgroundDrcM23ConflictExplainedRoute: typeof BackgroundDrcM23ConflictExplainedRoute
  BackgroundHezbollahCapabilitiesRoute: typeof BackgroundHezbollahCapabilitiesRoute
  BackgroundIsTheGazaCeasefireHoldingRoute: typeof BackgroundIsTheGazaCeasefireHoldingRoute
  BackgroundIsTheLebanonCeasefireHoldingRoute: typeof BackgroundIsTheLebanonCeasefireHoldingRoute
  BackgroundIsTheUsAtWarRoute: typeof BackgroundIsTheUsAtWarRoute
  BackgroundNorthKoreaRussiaMilitaryAllianceRoute: typeof BackgroundNorthKoreaRussiaMilitaryAllianceRoute
  BackgroundNuclearWeaponsByCountryRoute: typeof BackgroundNuclearWeaponsByCountryRoute
  BackgroundPakistanAfghanistanWarExplainedRoute: typeof BackgroundPakistanAfghanistanWarExplainedRoute
  BackgroundRedSeaCrisisRoute: typeof BackgroundRedSeaCrisisRoute
  BackgroundRussianCasualtiesUkraineRoute: typeof BackgroundRussianCasualtiesUkraineRoute
  BackgroundStraitOfHormuzRoute: typeof BackgroundStraitOfHormuzRoute
  BackgroundUsChinaGreatPowerRivalryExplainedRoute: typeof BackgroundUsChinaGreatPowerRivalryExplainedRoute
  BackgroundVenezuelaCubaCrisisExplainedRoute: typeof BackgroundVenezuelaCubaCrisisExplainedRoute
  BackgroundWhySudanIsAtWarRoute: typeof BackgroundWhySudanIsAtWarRoute
  BackgroundWillChinaInvadeTaiwanRoute: typeof BackgroundWillChinaInvadeTaiwanRoute
  BackgroundWillIndiaPakistanGoToWarAgainRoute: typeof BackgroundWillIndiaPakistanGoToWarAgainRoute
  BackgroundWorldWar3RiskRoute: typeof BackgroundWorldWar3RiskRoute
  BriefingDateRoute: typeof BriefingDateRoute
  DeepDiveSectionRoute: typeof DeepDiveSectionRoute
  BriefingIndexRoute: typeof BriefingIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ukraine-war-map': {
      id: '/ukraine-war-map'
      path: '/ukraine-war-map'
      fullPath: '/ukraine-war-map'
      preLoaderRoute: typeof UkraineWarMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/': {
      id: '/briefing/'
      path: '/briefing'
      fullPath: '/briefing/'
      preLoaderRoute: typeof BriefingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-dive/$section': {
      id: '/deep-dive/$section'
      path: '/deep-dive/$section'
      fullPath: '/deep-dive/$section'
      preLoaderRoute: typeof DeepDiveSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$date': {
      id: '/briefing/$date'
      path: '/briefing/$date'
      fullPath: '/briefing/$date'
      preLoaderRoute: typeof BriefingDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/world-war-3-risk': {
      id: '/background/world-war-3-risk'
      path: '/background/world-war-3-risk'
      fullPath: '/background/world-war-3-risk'
      preLoaderRoute: typeof BackgroundWorldWar3RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/will-india-pakistan-go-to-war-again': {
      id: '/background/will-india-pakistan-go-to-war-again'
      path: '/background/will-india-pakistan-go-to-war-again'
      fullPath: '/background/will-india-pakistan-go-to-war-again'
      preLoaderRoute: typeof BackgroundWillIndiaPakistanGoToWarAgainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/will-china-invade-taiwan': {
      id: '/background/will-china-invade-taiwan'
      path: '/background/will-china-invade-taiwan'
      fullPath: '/background/will-china-invade-taiwan'
      preLoaderRoute: typeof BackgroundWillChinaInvadeTaiwanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/why-sudan-is-at-war': {
      id: '/background/why-sudan-is-at-war'
      path: '/background/why-sudan-is-at-war'
      fullPath: '/background/why-sudan-is-at-war'
      preLoaderRoute: typeof BackgroundWhySudanIsAtWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/venezuela-cuba-crisis-explained': {
      id: '/background/venezuela-cuba-crisis-explained'
      path: '/background/venezuela-cuba-crisis-explained'
      fullPath: '/background/venezuela-cuba-crisis-explained'
      preLoaderRoute: typeof BackgroundVenezuelaCubaCrisisExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/us-china-great-power-rivalry-explained': {
      id: '/background/us-china-great-power-rivalry-explained'
      path: '/background/us-china-great-power-rivalry-explained'
      fullPath: '/background/us-china-great-power-rivalry-explained'
      preLoaderRoute: typeof BackgroundUsChinaGreatPowerRivalryExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/strait-of-hormuz': {
      id: '/background/strait-of-hormuz'
      path: '/background/strait-of-hormuz'
      fullPath: '/background/strait-of-hormuz'
      preLoaderRoute: typeof BackgroundStraitOfHormuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/russian-casualties-ukraine': {
      id: '/background/russian-casualties-ukraine'
      path: '/background/russian-casualties-ukraine'
      fullPath: '/background/russian-casualties-ukraine'
      preLoaderRoute: typeof BackgroundRussianCasualtiesUkraineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/red-sea-crisis': {
      id: '/background/red-sea-crisis'
      path: '/background/red-sea-crisis'
      fullPath: '/background/red-sea-crisis'
      preLoaderRoute: typeof BackgroundRedSeaCrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/pakistan-afghanistan-war-explained': {
      id: '/background/pakistan-afghanistan-war-explained'
      path: '/background/pakistan-afghanistan-war-explained'
      fullPath: '/background/pakistan-afghanistan-war-explained'
      preLoaderRoute: typeof BackgroundPakistanAfghanistanWarExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/nuclear-weapons-by-country': {
      id: '/background/nuclear-weapons-by-country'
      path: '/background/nuclear-weapons-by-country'
      fullPath: '/background/nuclear-weapons-by-country'
      preLoaderRoute: typeof BackgroundNuclearWeaponsByCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/north-korea-russia-military-alliance': {
      id: '/background/north-korea-russia-military-alliance'
      path: '/background/north-korea-russia-military-alliance'
      fullPath: '/background/north-korea-russia-military-alliance'
      preLoaderRoute: typeof BackgroundNorthKoreaRussiaMilitaryAllianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/is-the-us-at-war': {
      id: '/background/is-the-us-at-war'
      path: '/background/is-the-us-at-war'
      fullPath: '/background/is-the-us-at-war'
      preLoaderRoute: typeof BackgroundIsTheUsAtWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/is-the-lebanon-ceasefire-holding': {
      id: '/background/is-the-lebanon-ceasefire-holding'
      path: '/background/is-the-lebanon-ceasefire-holding'
      fullPath: '/background/is-the-lebanon-ceasefire-holding'
      preLoaderRoute: typeof BackgroundIsTheLebanonCeasefireHoldingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/is-the-gaza-ceasefire-holding': {
      id: '/background/is-the-gaza-ceasefire-holding'
      path: '/background/is-the-gaza-ceasefire-holding'
      fullPath: '/background/is-the-gaza-ceasefire-holding'
      preLoaderRoute: typeof BackgroundIsTheGazaCeasefireHoldingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/hezbollah-capabilities': {
      id: '/background/hezbollah-capabilities'
      path: '/background/hezbollah-capabilities'
      fullPath: '/background/hezbollah-capabilities'
      preLoaderRoute: typeof BackgroundHezbollahCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/drc-m23-conflict-explained': {
      id: '/background/drc-m23-conflict-explained'
      path: '/background/drc-m23-conflict-explained'
      fullPath: '/background/drc-m23-conflict-explained'
      preLoaderRoute: typeof BackgroundDrcM23ConflictExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/belarus-role-russia-ukraine-war': {
      id: '/background/belarus-role-russia-ukraine-war'
      path: '/background/belarus-role-russia-ukraine-war'
      fullPath: '/background/belarus-role-russia-ukraine-war'
      preLoaderRoute: typeof BackgroundBelarusRoleRussiaUkraineWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictsRoute: ConflictsRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UkraineWarMapRoute: UkraineWarMapRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BackgroundBelarusRoleRussiaUkraineWarRoute:
    BackgroundBelarusRoleRussiaUkraineWarRoute,
  BackgroundDrcM23ConflictExplainedRoute:
    BackgroundDrcM23ConflictExplainedRoute,
  BackgroundHezbollahCapabilitiesRoute: BackgroundHezbollahCapabilitiesRoute,
  BackgroundIsTheGazaCeasefireHoldingRoute:
    BackgroundIsTheGazaCeasefireHoldingRoute,
  BackgroundIsTheLebanonCeasefireHoldingRoute:
    BackgroundIsTheLebanonCeasefireHoldingRoute,
  BackgroundIsTheUsAtWarRoute: BackgroundIsTheUsAtWarRoute,
  BackgroundNorthKoreaRussiaMilitaryAllianceRoute:
    BackgroundNorthKoreaRussiaMilitaryAllianceRoute,
  BackgroundNuclearWeaponsByCountryRoute:
    BackgroundNuclearWeaponsByCountryRoute,
  BackgroundPakistanAfghanistanWarExplainedRoute:
    BackgroundPakistanAfghanistanWarExplainedRoute,
  BackgroundRedSeaCrisisRoute: BackgroundRedSeaCrisisRoute,
  BackgroundRussianCasualtiesUkraineRoute:
    BackgroundRussianCasualtiesUkraineRoute,
  BackgroundStraitOfHormuzRoute: BackgroundStraitOfHormuzRoute,
  BackgroundUsChinaGreatPowerRivalryExplainedRoute:
    BackgroundUsChinaGreatPowerRivalryExplainedRoute,
  BackgroundVenezuelaCubaCrisisExplainedRoute:
    BackgroundVenezuelaCubaCrisisExplainedRoute,
  BackgroundWhySudanIsAtWarRoute: BackgroundWhySudanIsAtWarRoute,
  BackgroundWillChinaInvadeTaiwanRoute: BackgroundWillChinaInvadeTaiwanRoute,
  BackgroundWillIndiaPakistanGoToWarAgainRoute:
    BackgroundWillIndiaPakistanGoToWarAgainRoute,
  BackgroundWorldWar3RiskRoute: BackgroundWorldWar3RiskRoute,
  BriefingDateRoute: BriefingDateRoute,
  DeepDiveSectionRoute: DeepDiveSectionRoute,
  BriefingIndexRoute: BriefingIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
