/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackgroundWorldWar3RiskRouteImport } from './routes/background.world-war-3-risk'
import { Route as BackgroundWillChinaInvadeTaiwanRouteImport } from './routes/background.will-china-invade-taiwan'
import { Route as BackgroundStraitOfHormuzRouteImport } from './routes/background.strait-of-hormuz'
import { Route as BackgroundRussianCasualtiesUkraineRouteImport } from './routes/background.russian-casualties-ukraine'
import { Route as BackgroundNuclearWeaponsByCountryRouteImport } from './routes/background.nuclear-weapons-by-country'
import { Route as BackgroundHezbollahCapabilitiesRouteImport } from './routes/background.hezbollah-capabilities'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundWorldWar3RiskRoute = BackgroundWorldWar3RiskRouteImport.update({
  id: '/background/world-war-3-risk',
  path: '/background/world-war-3-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundWillChinaInvadeTaiwanRoute =
  BackgroundWillChinaInvadeTaiwanRouteImport.update({
    id: '/background/will-china-invade-taiwan',
    path: '/background/will-china-invade-taiwan',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundStraitOfHormuzRoute =
  BackgroundStraitOfHormuzRouteImport.update({
    id: '/background/strait-of-hormuz',
    path: '/background/strait-of-hormuz',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundRussianCasualtiesUkraineRoute =
  BackgroundRussianCasualtiesUkraineRouteImport.update({
    id: '/background/russian-casualties-ukraine',
    path: '/background/russian-casualties-ukraine',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundNuclearWeaponsByCountryRoute =
  BackgroundNuclearWeaponsByCountryRouteImport.update({
    id: '/background/nuclear-weapons-by-country',
    path: '/background/nuclear-weapons-by-country',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackgroundHezbollahCapabilitiesRoute =
  BackgroundHezbollahCapabilitiesRouteImport.update({
    id: '/background/hezbollah-capabilities',
    path: '/background/hezbollah-capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/background/hezbollah-capabilities': typeof BackgroundHezbollahCapabilitiesRoute
  '/background/nuclear-weapons-by-country': typeof BackgroundNuclearWeaponsByCountryRoute
  '/background/russian-casualties-ukraine': typeof BackgroundRussianCasualtiesUkraineRoute
  '/background/strait-of-hormuz': typeof BackgroundStraitOfHormuzRoute
  '/background/will-china-invade-taiwan': typeof BackgroundWillChinaInvadeTaiwanRoute
  '/background/world-war-3-risk': typeof BackgroundWorldWar3RiskRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/hezbollah-capabilities'
    | '/background/nuclear-weapons-by-country'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/will-china-invade-taiwan'
    | '/background/world-war-3-risk'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/hezbollah-capabilities'
    | '/background/nuclear-weapons-by-country'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/will-china-invade-taiwan'
    | '/background/world-war-3-risk'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/background/hezbollah-capabilities'
    | '/background/nuclear-weapons-by-country'
    | '/background/russian-casualties-ukraine'
    | '/background/strait-of-hormuz'
    | '/background/will-china-invade-taiwan'
    | '/background/world-war-3-risk'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BackgroundHezbollahCapabilitiesRoute: typeof BackgroundHezbollahCapabilitiesRoute
  BackgroundNuclearWeaponsByCountryRoute: typeof BackgroundNuclearWeaponsByCountryRoute
  BackgroundRussianCasualtiesUkraineRoute: typeof BackgroundRussianCasualtiesUkraineRoute
  BackgroundStraitOfHormuzRoute: typeof BackgroundStraitOfHormuzRoute
  BackgroundWillChinaInvadeTaiwanRoute: typeof BackgroundWillChinaInvadeTaiwanRoute
  BackgroundWorldWar3RiskRoute: typeof BackgroundWorldWar3RiskRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/world-war-3-risk': {
      id: '/background/world-war-3-risk'
      path: '/background/world-war-3-risk'
      fullPath: '/background/world-war-3-risk'
      preLoaderRoute: typeof BackgroundWorldWar3RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/will-china-invade-taiwan': {
      id: '/background/will-china-invade-taiwan'
      path: '/background/will-china-invade-taiwan'
      fullPath: '/background/will-china-invade-taiwan'
      preLoaderRoute: typeof BackgroundWillChinaInvadeTaiwanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/strait-of-hormuz': {
      id: '/background/strait-of-hormuz'
      path: '/background/strait-of-hormuz'
      fullPath: '/background/strait-of-hormuz'
      preLoaderRoute: typeof BackgroundStraitOfHormuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/russian-casualties-ukraine': {
      id: '/background/russian-casualties-ukraine'
      path: '/background/russian-casualties-ukraine'
      fullPath: '/background/russian-casualties-ukraine'
      preLoaderRoute: typeof BackgroundRussianCasualtiesUkraineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/nuclear-weapons-by-country': {
      id: '/background/nuclear-weapons-by-country'
      path: '/background/nuclear-weapons-by-country'
      fullPath: '/background/nuclear-weapons-by-country'
      preLoaderRoute: typeof BackgroundNuclearWeaponsByCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background/hezbollah-capabilities': {
      id: '/background/hezbollah-capabilities'
      path: '/background/hezbollah-capabilities'
      fullPath: '/background/hezbollah-capabilities'
      preLoaderRoute: typeof BackgroundHezbollahCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BackgroundHezbollahCapabilitiesRoute: BackgroundHezbollahCapabilitiesRoute,
  BackgroundNuclearWeaponsByCountryRoute:
    BackgroundNuclearWeaponsByCountryRoute,
  BackgroundRussianCasualtiesUkraineRoute:
    BackgroundRussianCasualtiesUkraineRoute,
  BackgroundStraitOfHormuzRoute: BackgroundStraitOfHormuzRoute,
  BackgroundWillChinaInvadeTaiwanRoute: BackgroundWillChinaInvadeTaiwanRoute,
  BackgroundWorldWar3RiskRoute: BackgroundWorldWar3RiskRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
